apiVersion: v1
kind: Service
metadata:
  name: nautos-app
  labels:
    app: nautos-app
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: nautos-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
