apiVersion: v1
kind: Service
metadata:
  name: nautos-worker
  labels:
    app: nautos-worker
    component: api
spec:
  type: ClusterIP
  # Only route traffic to the API pods, not Celery pods
  selector:
    app: nautos-worker
    component: api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
