FROM python:3.12-slim

WORKDIR /worker

RUN pip install uv

COPY pyproject.toml ./
RUN uv pip install --system -e ".[dev]"

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
